# Generated by Django 4.2.3 on 2023-11-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_retaineritems_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='retainerinvoice',
            name='advance',
            field=models.DateField(null=True),
        ),
    ]
