# Generated by Django 4.1 on 2023-04-06 17:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0003_alter_customer_details_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer_details',
            new_name='company_details',
        ),
    ]
