# Generated by Django 4.2.3 on 2023-11-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_retainerinvoice_advance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retainerinvoice',
            name='advance',
            field=models.IntegerField(null=True),
        ),
    ]
