# Generated by Django 4.1 on 2023-04-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_rename_customer_details_company_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/patient'),
        ),
    ]
