# Generated by Django 4.2 on 2023-04-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_purchase_sales_unit_additem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='Cost_price',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='Selling_price',
        ),
    ]
