# Generated by Django 4.2.3 on 2023-12-06 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0007_retaineritems_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_item',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.additem'),
        ),
    ]
