# Generated by Django 4.2 on 2023-04-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0007_remove_purchase_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='p_desc',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additem',
            name='s_disc',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
