# Generated by Django 4.2 on 2023-04-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0008_additem_date_additem_p_desc_additem_s_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='history',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
