# Generated by Django 4.2 on 2023-04-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_additem_p_price_additem_s_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additem',
            old_name='s_disc',
            new_name='s_desc',
        ),
    ]
