# Generated by Django 4.2.3 on 2023-12-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_alter_retinvoicereference_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retinvoicereference',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='salesorderreference',
            old_name='customer',
            new_name='user',
        ),
    ]
