# Generated by Django 4.2 on 2023-04-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0011_rename_s_disc_additem_s_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='satus',
            field=models.TextField(default='active'),
        ),
    ]
