# Generated by Django 4.2 on 2023-04-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0013_additem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='user',
        ),
    ]
